### PR TITLE
Information not showing on drag

### LINKED ISSUE #593: The "Give Feedback" button/option can be wrongly dragged in the sidebar
**[Notes]:**
- Given that the "Give Feedback" button and option are the only ones that can be dragged, we should restrict this behavior in order to have them all behave consistently.

**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.1.1rc2) installed.
- You are not logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click and drag the "Give Feedback" button in the sidebar.
3. Observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- A CSS code line is displayed in the sidebar.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible if you are logged into "Firefox Notes" and you drag the "Give Feedback" option from the "Notes" menu. However in that case the "Give Feedback" string is displayed into the sidebar.
- Attached a screen recording of the issue:
rec of the issue

### PR DESCRIPTION
**Pull request by anweshknayak**
fixes #593 
Seems like the problem was with using inline styling. Once it is removed no such info is shown.

### CODE REVIEW

**Comment by anweshknayak** [comment]
@Natim

**Comment by Natim** [comment]
It is better because it doesn't display anything anymore in the pad, but we still have the drag and drop zone showing. However it doesn't apply to the other button.

**Comment by anweshknayak** [comment]
@Natim done

**Comment by Natim** [comment]
We used to have a onClick that was using the tab API.

**Comment by anweshknayak** [comment]
@Natim using style="pointer-events: none;" did the trick.

**Comment by Natim** [comment]
No it didn't really because:

- [ ] We don't have the hover color change when hovering the button anymore
- [ ] When we click it display the menu instead of opening the feedback tab

**Comment by Natim** [comment]
Superseeded by https://github.com/mozilla/notes/pull/615

**Pull request closed without merging**
