### PR TITLE
Lint files on commit and copy Circle artifacts

### PR DESCRIPTION
**Pull request by pdehaan**

### CODE REVIEW

**Comment by vladikoff** [comment]
@pdehaan the CI on this failed or something O_o

**Comment by vladikoff** [comment]
The hook didn't kick in

**Comment by pdehaan** [comment]
Which may also explain why #54 failed and greenkeeper wasn't activated [again].

**Comment by vladikoff** [comment]
@pdehaan working for me here: https://github.com/mozilla/notes/pull/56

**Comment by vladikoff** [comment]
@pdehaan rebase maybe?

**Pull request merged**
