### PR TITLE
795 multi notes ux polish

### LINKED ISSUE #795: Multi-note UX polish
Bravo! This is the maybe the happiest moment I've had at Mozilla. It's so close!

Some finer points:
- [x] Shorten header to 40px
- [x] Shorten formatting bar to 36px
- [x] Vertically center ⋯ icon in formatting bar
- [x] Vertically center ⋯ icon in footer
- [x] Inset ⋯ button 8px from right 
- [x] Inset Sync icon 16px from left
- [x] Reduce row heights on list view
- [x] Add **Make Plain Text* and conversely **Make Rich Text** #799
- [x] When you create a note, say `smallnote`, the letter is will be capital in the ListView aka `Smallnote` (from vlad / ryan testing)
- [x] Windows shows no change to font weight of note title & timestamp. Try font-weight: 600
- [x] When a user deletes a note, it should trigger a manual sync
- [x] Put 1px of negative padding or margin on the bottom of the list view so that when you scroll down to the bottom of a long list of notes, the last item does not have double lines. screen shot 2018-03-23 at 10 38 35 am copy
- [x] Add vertical spacing to  ⋯ menu items
- [x] Make the formatting bar overflow hidden no wrap
- [x] Inherit view/subview animation from our Photon menu system #813
- [x] Add the clear formatting button to the formatting toolbar (so users can remove `code`) #814
- [x] Make sure that when users click **Sign in to Sync** that it opens signin and not registration #815 

Change requests (can I change my mind?):
- [x] Add a "Back to all notes" tooltip on the back button
- [x] During sync, made the spinning sync icon grey not blue
- [x] If first line is A, and subsequent lines are B, C and D, the summary should be B C D (currently no spaces, BCD)
- [x] Make the footer background colour #f7f7f7 (so it looks more like the Photon bookmark menu footer)
- [x] I was wrong about showing "Sync with" on hover. It should just be a tooltip on the sync icon. It will fit more information and be easier to read.

image

image

image

### PR DESCRIPTION
**Pull request by sebastienbarbier**
Fix #795

### CODE REVIEW

**Comment by vladikoff** [comment]
@sebastienbarbier issues with the CI

**Comment by sebastienbarbier** [comment]
On it right now 😅
```
 19:16  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword
```
Seams like eslint doesn't like the `font: message-box` and refuse to take my `// eslint-disable-line`

**Comment by vladikoff** [comment]
@sebastienbarbier try:

```
/* eslint-disable */

alert('foo');

/* eslint-enable */

``` ?

**Comment by sebastienbarbier** [comment]
Fixed it with `font: message-box, sans-serif;`

**Pull request merged**
