### PR TITLE
Use 100vh so that the footer doesn't bounce.

### LINKED ISSUE #600: The bottom part wrongly bounces while resizing the window
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-01-19) installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Vertically resize the browser.
3. Observe the bottom part of the "Notes" sidebar.

[Expected result]:
- Nothing happens with the bottom part, it's steady.

[Actual result]:
- The bottom part bounces.

[Notes]:
- This issue is also reproducible if you diagonally resize the browser.
- This issue is also reproducible with Firefox Notes installed from Test Pilot experiment [page](https://testpilot.firefox.com/experiments/notes) and with Firefox Notes v2.1.1.rc2.
- Here is a screen recording of the issue:
look at the bottom

### PR DESCRIPTION
**Pull request by Natim**
Fixes #600 via @johngruen

### CODE REVIEW

**Comment by Natim** [comment]
Hi @Softvision-CristinaBadescu 
Can I let you try this branch and see if it fixes #600?
[addon-fixes-600-questionmark.zip](https://github.com/mozilla/notes/files/1652650/addon-fixes-600-questionmark.zip)

**Comment by Softvision-CristinaBadescu** [comment]
Hello @Natim, thanks for looking into this. 

I've tested this issue with the provided build, but it didn't solved the bug because it is still reproducible on latest Nightly build 60.0a1 (2018-01-22), on Windows 10 x64 and Ubuntu 14.04 x64.

However, this issue is not reproducible on Mac 10.12.6, on latest Nightly build 60.a1 (2018-01-22), using Firefox Notes v2.2.0dev (custom build 2018-01-23), Firefox Notes from Test Pilot experiments [page](https://testpilot.firefox.com/experiments/notes) or the provided build from your last comment.

**Comment by Natim** [comment]
Ok I guess it is an improvment then. I am merging this and we will figure it out later for other impacted releases.

**Comment by Natim** [comment]
I had to revert that because the scrolling of the editor was broken with it.

**Pull request merged**
