### PR TITLE
Preparing 3.0.0 release

### PR DESCRIPTION
**Pull request by vladikoff**
Things to test:

* Add send-to-notes context menu (#655)
* Add "Export as HTML" option (#695)
* Use React.js states to render the add-on frontend (#550)

cc @SoftVision-EmilPasca

### CODE REVIEW

**Comment by vladikoff** [comment]
[https://1228-91073350-gh.circle-artifacts.com/0/tmp/circle-artifacts.MicZiHM/firefox_notes-3.0.0.zip](https://1228-91073350-gh.circle-artifacts.com/0/tmp/circle-artifacts.MicZiHM/firefox_notes-3.0.0.zip)

**Comment by Natim** [comment]
- [ ] #701 
- [ ] #702

**Comment by sebastienbarbier** [comment]
[notes_3.0.0rc2.zip](https://github.com/mozilla/notes/files/1737144/notes_3.0.0rc2.zip)

**Comment by vladikoff** [comment]
Let's add a metrics event for Export to HTML

**Comment by vladikoff** [comment]
- [ ] https://github.com/mozilla/notes/issues/705
- [ ] https://github.com/mozilla/notes/issues/711
- [ ] https://github.com/mozilla/notes/issues/708
- [ ] https://github.com/mozilla/notes/issues/707
- [ ] Fix border to the right of the sync button...

**Pull request merged**
