### PR TITLE
Bulgarian translation

### PR DESCRIPTION
**Pull request by AdmiralAnimE**

### CODE REVIEW

**Comment by vladikoff** [comment]
Please use Pontoon for this. Thanks!

**Comment by AdmiralAnimE** [comment]
Well okay, but there is no bulgarian there...

**Comment by vladikoff** [comment]
Pontoon link: https://pontoon.mozilla.org/projects/test-pilot-notes/

**Comment by cedricium** [comment]
@vladikoff I'm not 100% sure how Pontoon works but in that link to the Notes Pontoon, there is no Bulgarian listed for @AdmiralAnimE to add their translations. Are they able to add it manually or does someone else need to add Bulgarian to the list of languages?

**Comment by vladikoff** [comment]
@flodolo would know

**Comment by flodolo** [comment]
You can request the project, locale managers can then decide if they want the project to be enabled or not (I don't think they will say no, given there's a volunteer willing to translate it)
https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/teams_projects.html#requesting-a-project

Also, CC @StoyanDimitrov

**Comment by StoyanDimitrov** [comment]
If the Test Pilot site is not a prequisite I'll enable it. @AdmiralAnimE, please get in touch with the team to discuss the details. You can use one ot the channels at the bottom of the page: https://wiki.mozilla.org/L10n:Teams:bg

**Comment by flodolo** [comment]
Yes, Test Pilot is not needed, each experiment can be localized on its own.

**Comment by Natim** [comment]
@flodolo could you activate bulgarian locale on Pontoon? https://pontoon.mozilla.org/bg/test-pilot-notes/ show a 404

**Comment by Natim** [comment]
Sorry I missed your message, please discard my message.

**Pull request closed without merging**
