### PR TITLE
Change sync text to black in footer

### PR DESCRIPTION
**Pull request by sebastienbarbier**

### CODE REVIEW

**Comment by Natim** [comment]
I think the Open login should stay grey. Same for confirm your account.

**Comment by sebastienbarbier** [comment]
Change styling to have lighter color if loading or not clickable.
grey-text-if-not-clickable-1
grey-text-if-not-clickable-2

**Comment by Natim** [comment]
- [ ] Hover on Synced at should change the icon to blue (without animation)
- [ ] Verify your account should not be clickable
- [ ] Reconnect to sync should be clickable

**Comment by Natim** [comment]
[notes-2.3.0dev4.zip](https://github.com/mozilla/notes/files/1729060/notes-2.3.0dev4.zip)

**Pull request merged**
