### PR TITLE
Add Keyboard Shortcut

### LINKED ISSUE #176: Consider a keyboard shortcut to open the notes sidebar?
I can open history with ctrl-h and bookmarks with ctrl-b. It would be great if I could open notes with alt-n or something.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #176

### CODE REVIEW

**Comment by Natim** [comment]
I also tried `Ctrl+Shift+N` without luck. @flodolo shall we plan on localize the shortcut?

**Comment by flodolo** [comment]
> I also tried Ctrl+Shift+N without luck. @flodolo shall we plan to localize the shortcut?

I'm not sure. This is a shortcut, not an acccesskey, so normally locales follow English.

If it opens the Edit menu, it means you're triggering accesskeys instead of a shortcut (like CMD+T to open a new tab on Mac).

**Comment by Natim** [comment]
Let's go with `Ctrl+Shift+L` which seems to be the first available letter...

**Comment by Natim** [comment]
@vladikoff suggested `Alt+Shift+W` which seems to work as well.

**Pull request merged**
