### PR TITLE
Preparing 2.2.0 release

### PR DESCRIPTION
**Pull request by Natim**
Let's start getting ready for the next release :D

[notes-2.2.0rc1.zip](https://github.com/mozilla/notes/files/1668089/notes-2.2.0rc1.zip)

- [x] https://github.com/mozilla/notes/issues/618
- [x] https://github.com/mozilla/notes/issues/568
- [x] #574 
- [x] #591
- [x] https://github.com/mozilla/notes/issues/623
- [x] https://github.com/mozilla/notes/issues/627
- [x] Avoid truncate on update...
- [x] #631 
- [x] #638
- [x] #642
- [x] #644 
- [x] https://github.com/mozilla/notes/issues/656
- [x] https://github.com/mozilla/notes/issues/623
- [x] #662

### CODE REVIEW

**Comment by Natim** [comment]
[notes-2.2.0rc2.zip](https://github.com/mozilla/notes/files/1668378/notes-2.2.0rc2.zip)

**Comment by vladikoff** [comment]
TODO:

- [ ] https://github.com/mozilla/notes/issues/623

**Comment by Natim** [comment]
[notes-2.2.0rc3.zip](https://github.com/mozilla/notes/files/1689093/notes-2.2.0rc3.zip)

**Comment by Natim** [comment]
[notes-2.2.0rc4.zip](https://github.com/mozilla/notes/files/1689457/notes-2.2.0rc4.zip)

**Comment by Natim** [comment]
[notes-2.2.0rc5.zip](https://github.com/mozilla/notes/files/1689535/notes-2.2.0rc5.zip)

**Comment by Natim** [comment]
[notes-2.2.0rc6.zip](https://github.com/mozilla/notes/files/1695753/notes-2.2.0rc6.zip)

**Comment by Natim** [comment]
[notes-2.2.0rc7.zip](https://github.com/mozilla/notes/files/1711612/notes-2.2.0rc7.zip)

**Comment by Natim** [comment]
[notes-2.2.0rc8.zip](https://github.com/mozilla/notes/files/1711707/notes-2.2.0rc8.zip)

**Comment by Natim** [comment]
[notes-2.2.0rc9.zip](https://github.com/mozilla/notes/files/1711812/notes-2.2.0rc9.zip)

**Comment by Natim** [comment]
@pdehaan The insecable space in 515bd16 was reverted here: https://github.com/mozilla/notes/commit/82c93555d48ce822d57fb9a3654079d7494a5274

**Comment by Natim** [comment]
🔥

**Pull request merged**
