### PR TITLE
Add strike plugin.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Natim** [comment]
@Reinmar Do you know where I can find similar SVG for the strikethrough feature? https://github.com/ckeditor/ckeditor5-basic-styles/tree/master/theme/icons

In your opinion should I rather try to contribute that directly to the ckeditor5-basic-styles?

**Comment by Reinmar** [comment]
> In your opinion should I rather try to contribute that directly to the ckeditor5-basic-styles project?

If you could make a PR with the feature itself, we can add an icon for it. [We're going to create a new official theme soon anyway](https://github.com/ckeditor/ckeditor5/issues/645) so if the icon is part of ckeditor5-basic-styles we'll ensure then that it's consistent with the other ones.

**Comment by Natim** [comment]
It kinda works but I have the following issues:

- [ ] The shortcut CTRL+ALT+S doesn't works
- [ ] The SVG icon doesn't show up in the toolbar.

**Comment by vladikoff** [comment]
@Natim In v1.9.0 we used `CMD + SHIFT + X` for this

**Comment by Natim** [comment]
> In v1.9.0 we used CMD + SHIFT + X for this

That's also @Commander advice here: https://github.com/ckeditor/ckeditor5-basic-styles/pull/58#discussion_r151722443

**Pull request merged**
