### PR TITLE
Add support for links

### PR DESCRIPTION
**Pull request by cedricium**
This is the initial implementation for supporting links (#233). With these changes,
links will automatically be created from anything that begins with `http://`
or `https://`. That includes any typed or pasted text.

The changes in the CSS make it so that the Quill link editing UI tooltip is
no longer shown. In order to open a link, the user must mouse over the link
and right-click for the context menu or <kbd>Ctrl/Cmd</kbd>+<kbd>Left Click</kbd> to open in a new tab.

**What Needs to Be Added:**
- [x] link mouse click events added to analytics - **completed: 877af94**
- [x] cursor mouseover behavior and appearance - **completed: 877af94**

### CODE REVIEW

**Comment by vladikoff** [comment]
@cedricium great start!!

Two things I noticed:

## 1. links to do not open

when clicked:

link


## 2. typing out urls, it's not easy to get out of the "URL" styling:

link2

**Comment by Natim** [comment]
For the second bug, the goal would be to remove the link as soon as it is not a valid link anymore.

**Comment by cedricium** [comment]
1. I wasn't sure what the expected behavior should be. Because this is text editor, links are not inherently clickable since editing a notepad is in the 'editing' state, not the 'readable' state. But I can change the behavior and make the links clickable for Notes purpose.
2. Once you add whitespace after a url, the link is created. Hitting `[Backspace]` begins editing the link immediately, whereas Google Docs for example removes the link after the first `[Backspace]` to allow users to make edits. I will go ahead and try to replicate this behavior as well.

**Comment by vladikoff** [comment]
> But I can change the behavior and make the links clickable for Notes purpose.

👍 

> Hitting [Backspace] begins editing the link immediately

Yea with the default UI that we hide there was a "remove" button, but because we are getting rid of it we need a way to get out of link editing. If it is not possible to do then we will need to find another way. (Maybe by bringing back the UI and making it simpler).

**Comment by cedricium** [comment]
@vladikoff let me know if this latest commit fixes the issues, I think it should. Whenever you delete the whitespace character after the link then begin typing, the `link` formatting should be removed. Links are clickable as well.

I tried implementing the `link-clicked` analytics as well, or so I thought. Let me know if I did that correctly.

**Comment by vladikoff** [comment]
@cedricium works really well! Doing so final testing before merging :)

**Comment by vladikoff** [comment]
@cedricium Hey, so the only change we want to make is:

If the link starts with https:// http:// it should edit the link when you edit the text.

Example:
link2

so in the gif above, If i edit the link it should go to `Firefox` instead of `Firefox for iOS`

**Comment by cedricium** [comment]
@vladikoff I'll see what I can do! 👍

**Comment by Natim** [comment]
@cedricium I added some debounce as well as links modification handling. Can you both validate with @vladikoff that it works as expected?

**Comment by Natim** [comment]
Apparently my commit breaks pasting links.

**Comment by cedricium** [comment]
@Natim I removed your debounce work as it seemed to be messing with the functionality of links. If possible, I'd like to have this latest commit sanity tested to verify the issues #252, #254, and #255 were actually resolved. If that's good, then I'd like to add back in debounce and continue working on the rest of the links issues.

cc @vladikoff

**Comment by Natim** [comment]
I am going to land this and we can iterate from it.

**Comment by vladikoff** [comment]
awww yessss , amazing work @cedricium // @Natim 

🎉

**Pull request merged**
