### PR TITLE
Add release steps.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by vladikoff** [comment]
@Natim how does this work for point releases, see https://github.com/mozilla/notes/issues/214 ?

**Comment by vladikoff** [comment]
from meeting: We also need to add a step for QA: "Send release to QA a day before publishing..."

**Comment by Natim** [comment]
> Send release to QA a day before publishing...

How does this works? Are we creating a branch that they can try out?

**Comment by Natim** [comment]
> how does this work for point releases?

It works exactly the same way I guess.

**Comment by vladikoff** [comment]
Thanks @Natim !!

**Pull request merged**
