### PR TITLE
Fixes https://github.com/mozilla/notes/issues/1209

### PR DESCRIPTION
**Pull request by TruptiM18**
Hi,

Fix for https://github.com/mozilla/notes/issues/1209 has been added by making following changes:
**Problem Description:**
The List View cannot be scrolled using the keyboard
**Solution:**

1. 

'keydown' event for 'ArrowUp' and 'ArrowDown' keys has been handled by adding an event handler 'handleKeyPress' in src/sidebar/app/components/ListPanel.js.

2. 

Pseudo class "focus" has been added in src/sidebar/static/scss/list.scss to add background color to currently selected note.

Please review the changes and let me know your comments/suggestions.

Thanks!

### CODE REVIEW

**Comment by TruptiM18** [comment]
Hi @vladikoff.
Can you please review this pull request and let me know your comments? 
I am looking forward to get it reviewed as this is my first PR. 
Thanks

**Comment by TruptiM18** [comment]
Hi @vladikoff,
Have you had a chance to review this PR?
Thanks.

**Comment by vladikoff** [comment]
Gonna take a look at it soon, sorry for the delay

**Comment by TruptiM18** [comment]
No problem!

**Comment by TruptiM18** [comment]
Hi @vladikoff,
Can you please review this PR?

**Comment by vladikoff** [comment]
Thanks @TruptiM18 !

**Comment by TruptiM18** [comment]
Thank you @vladikoff !

**Pull request merged**
