### PR TITLE
Implement animation on Sync Toolbar

### PR DESCRIPTION
**Pull request by sebastienbarbier**
After short discussion with @Natim asking for help about animations, I took a day to implement a first version and share some ideas.

Should match all use case defined in specifications, and be easy to manipulate using javascript `function setAnimation()`.

**Login process :**
v1 animation login

**Syncing process :**
v1 animation syncing

This PR take the initiative to remove all sync*.svg and feedback*.svg and **inject them as inline svg** instead to allow path fill override using css to have transition animation.
Would be nice to embed them as component somehow but it require to think about which stack to adopt and is out of this scope.

Hope this will be usefull and start some talks about how to improve 👍.

### CODE REVIEW

**Comment by Natim** [comment]
@ryanfeeley do you know how it should look like with the dark theme?

**Comment by ryanfeeley** [comment]
Fantastic! I haven't thought about dark theme. @cedricium is that your baby?

**Comment by cedricium** [comment]
@ryanfeeley I'd like to think so 😊 

@sebastienbarbier looks great! If you do need help or have any questions about the dark theme just give me a shout out.

**Comment by ryanfeeley** [comment]
@sebastienbarbier The Firefox Design Systems Group has defined some numbers of animation like easing. Possible to use these? http://design.firefox.com/photon/motion/duration-and-easing.html

**Comment by sebastienbarbier** [comment]
@ryanfeeley No problems, I did apply those and here is what it looks like now :  

v2 animation login
v2 animation login dark

@cedricium I did some changes, can you give a look and let me know your thoughts about it ? 🙂

**Comment by cedricium** [comment]
Hey @sebastienbarbier, just cloned your repo and tested the animations myself. Seems to be broken on my machine (`13.3" MacBook Air; OSX 10.11.6 - El Capitan; FF Nightly 57.0a1`). Below are a couple screenshots of what I saw:

screen shot 2017-10-22 at 10 39 24 pm
screen shot 2017-10-22 at 11 00 16 pm
screen shot 2017-10-22 at 11 00 32 pm
screen shot 2017-10-22 at 11 00 44 pm

**Comment by cedricium** [comment]
@sebastienbarbier made a screen-recording of what I saw. 

Here's the link to the video: https://drive.google.com/open?id=0B8eAjGoZ-OWkdmZxVWJyVzZtdzA

This was done after:
1. Cloning your `sebastienbarbier/notes` repo.
2. `cd`ing to the new `sebastienbarbier/notes` repo and running `npm install`.
3. Once install was complete, I ran `npm run start-nightly`; once the browser came up that's where I started the video.

**Comment by sebastienbarbier** [comment]
All right I gonna need some help here since I am not sure what to do 😟
It does work for me on `56.0`, `Developer 57.0b10 (64 bits)`, and `Nightly 58.0a1 (2017-10-22) (64-bit)`. 

@cedricium Do you have an other version you could try on ? Is there a way for me to get 57.0a1 on my machine ?
Can anyone else give a try and let me know if an other version produce this issue ?

I am not sure blaming versioning is right. I am on `MacOS 10.13, MacbookPro 15"` ... which other criteria could be involved ?

My guess is there is some conflict with the material context menu, but it will be difficult to fix without being able to reproduce locally.

**Comment by cedricium** [comment]
Just tried regular FF (`v56.0`) and it looks the same way as the video above. I'm not sure if you can get `57.0` for Nightly, but I could try upgrading to `58.0` and see if the problem is fixed there.

Would definitely be helpful if others tried reproducing the issue on their own machines and reporting back.

**Comment by Natim** [comment]
I tried it and I cannot reproduce it myself

**Comment by Natim** [comment]
@cedricium can you try this build? 
@ryanfeeley can you try it as well and give some feedback or signoff?
[addon-2.0.0a5-anim.zip](https://github.com/mozilla/notes/files/1414772/addon-2.0.0a5-anim.zip)

**Comment by SoftVision-EmilPasca** [comment]
After you sign-in with your credentials, whenever clicking the "Sync" button you can observe that for a fraction of a second the "Opening Login...." message is displayed in the status bar.
footbar_animation_login

**Comment by sebastienbarbier** [comment]
@SoftVision-EmilPasca Just pushed a fix to this bug 👍, thanks for finding it.

**Pull request merged**
