### PR TITLE
Alternative loading screen

### PR DESCRIPTION
**Pull request by sebastienbarbier**
Could this be an option ?

loadingscreen

### CODE REVIEW

**Comment by vladikoff** [comment]
@antlam thoughts?

**Comment by vladikoff** [comment]
please rebase

**Comment by antlam** [comment]
> Could this be an option ?

Skeleton UI is cool and there are perceived perf benefits too. 

But I think it also needs more thought.. E.g. what does the animation look like, how much of the actual UI should it imitate? and what our our motion design guidelines here (from Photon), etc...

**Comment by vladikoff** [comment]
per @antlam's comment let's focus on the rest of the bugs and issues. maybe bring this back later.

**Pull request closed without merging**
