### PR TITLE
Uplift master into ckbuilt

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by vladikoff** [comment]
@cedricium updated your branch with latest commits from master

**Comment by cedricium** [comment]
I'll have several changes soon, which commit do I remove when rebasing - will it be the same as last time (as outlined in #798)?

**Comment by vladikoff** [comment]
@cedricium yeap same one.

**Comment by cedricium** [comment]
I'll give it a try once I'm home!

**Pull request merged**
