### PR TITLE
Handle full storage errors

### LINKED ISSUE #1022: [Android] You are wrongly logged out from "Notes", if the "Notes Storage Full" message is tapped
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2003) installed.
- Have enough notes in order to reach the maximum storage limit.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on the "New Note" button and write something.
3. Tap on the "Notes Storage Full" message from the bottom of the side menu.

**[Expected result]:**
- The side menu is closed and the "Notes" app can still be used.

**[Actual result]:**
- You are logged out from "Notes".

**[Notes]:**
- The notes that were created after the limit is reached will be deleted after log out.
- Attached a screen recording of the issue:
rec of the issue

### LINKED ISSUE #1023: [Android] The "Notes synced!" banner message is wrongly displayed after the maximum storage limit is reached
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2003) installed.
- Have enough notes in order to reach the maximum storage limit.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on the "New Note" button and write something.
3. Dismiss the sidebar and tap on the back button.
4. Dismiss the sidebar again and swipe down in order to refresh the page.
5. Observe the bottom part of the application.

**[Expected result]:**
- The "Notes synced!" banner message is not displayed, since the content is not synced.

**[Actual result]:**
- The "Notes synced!" banner message is displayed.

**[Notes]:**
- Attached a screen recording of the issue:
rec of the issue 1

### LINKED ISSUE #1024: [Android] The side menu cannot be dismissed if it is opened in the notes view mode
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2003) installed.
- Have enough notes in order to reach the maximum storage limit.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on the "New Note" button and write something.
3. Swipe left on the side menu and observe the behavior.

**[Expected result]:**
- The side menu is dismissed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- If the swipe action is performed over the "Log out" button, you are wrongly logged out from "Notes".
- If the swipe action is performed over the "Feedback" button, the feedback page is opened.
- The issue is not reproducible if you tap outside the side menu.
- Attached a screen recording of the issue:
rec of the issue 2

### LINKED ISSUE #1036: [Android] A white screen is wrongly displayed after tapping the back button, if the maximum storage limit is reached
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2046 custom built on 07.05.2018) installed.
- Have enough notes in order to reach the maximum storage limit.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap the "New Note" button and write something.
3. Tap the "Back" button from the top left part of the application.
4. Observe the behavior

**[Expected result]:**
- You are successfully returned to the list view.

**[Actual result]:**
- A white screen is displayed.

**[Notes]:**
- After encountering the issue, the white screen is displayed after any action taken, until you log out or close the application.
- Attached a screen recording of the issue: 
rec of the issue

### PR DESCRIPTION
**Pull request by sebastienbarbier**
- [x] Crash on back button if storage limit is reached (fix #1036 )
- [x] Disable logout on "Notes Storage Full" message error (fix #1022)
- [x] Remove "Notes synced!" notification if storage limit is reached (fix #1023)
- [x] Side menu cannot be dismissed (fix #1024)
- [x] notify the user about having reached full storage capacity.
- [x]  display errors in editor header

### CODE REVIEW

**Comment by sebastienbarbier** [comment]
Having an issue with the Drawer, I had to fork react-navigation and temporarily use it in notes.
Code has been submit to the main repo, will be discussed with other contributors, and hopefully be integrated in next release 👍 (https://github.com/react-navigation/react-navigation/pull/4202).

**Comment by sebastienbarbier** [comment]
**Suggestion**: error snackbar to notify the user about reaching storage limit, duration is 3 sec.

errorsnackbar
errorsnackbar2

**Current behaviour**: if the error log out the user, we open the drawer instead.

**Comment by sebastienbarbier** [comment]
@antlam is a red snackbar not too agressive ? we could have it yellow ... but this match the error color from the drawer.

**Comment by sebastienbarbier** [comment]
storageerror

@antlam: On error, I implemented in such a way that we keep the error and never go back to the note title. If syncing is performed successfully, we wait 2s with 'Synced' message and then display the note title.

I also reduced snackbars durations to match values defined by Material UI and made the error one short instead of long 👍

**Comment by antlam** [comment]
looks good to me! @vladikoff 

I think "Storage full" might be enough but we should loop in Content for some help with the copy in general too.

**Pull request merged**
