### PR TITLE
The sync button no longer dislocates on being clicked

### PR DESCRIPTION
**Pull request by himanish-star**
fixes : #526 

Changes can be previewed below

ezgif com-video-to-gif 3

### CODE REVIEW

**Comment by himanish-star** [comment]
@Natim , Could you have a look into this. As the CI test which failed has nothing to do with my commit as I have only made a minor change

**Comment by Natim** [comment]
Is it normal that it doesn't turn into a Syncing change message?

**Comment by himanish-star** [comment]
>Is it normal that it doesn't turn into a Syncing change message?

Oh sorry, didn't notice that this got changed too. I will correct this.

**Comment by Natim** [comment]
@himanish-star can you try to keep button and add a display: inline for the button in the CSS?

**Comment by himanish-star** [comment]
@Natim , currently I'm facing some issues with my browser. When I click the sync button the login page opens up and then when I try to log in I get this
screenshot from 2018-01-08 19-43-44
I'm really trying to find out why this is happening. I was playing around with the settings today for one of the projects named pdf.js to try an install a plugin and from then on my sync is not working. Please excuse me for a while as I'm trying to resurrect back things. I will soon make the channges

**Comment by Natim** [comment]
You can probably use a new profile for your tests? Or use `npm run start`?

**Comment by himanish-star** [comment]
> @himanish-star can you try to keep button and add a display: inline for the button in the CSS?

Yeah sure doing that now.

> Is it normal that it doesn't turn into a Syncing change message?

Well on clicking the sync button previously before the changes also nothing of this sort used to happen. As I recently tested the master branch and found out that it doesn't turn into a Syncing change message.

**Comment by himanish-star** [comment]
>@himanish-star can you try to keep button and add a display: inline for the button in the CSS?

@Natim , nothing seems to work. Only if use `<span>` instead of `<button>` things become correct. The display inline doesn't fix this as I tried doing so and it didn't work

**Pull request merged**
