### PR TITLE
colour changed for max size warning 

### PR DESCRIPTION
**Pull request by anweshknayak**
fixes a part of #618 
Changed color according to this : https://design.firefox.com/photon/components/message-bars.html#warning

@Natim I am not sure about the second one. Couldn't find the properties respective to it. 
Having a hard time debugging the app. Can you recommend any tools for the same?

### CODE REVIEW

**Comment by Natim** [comment]
@vladikoff told me that the good think to do was to use the browser toolbox (ctrl+alt+shift+I)

**Comment by anweshknayak** [comment]
Doesn't help :confused: . Still first part of this issue is fixed 
screenshot from 2018-01-29 15 56 38

**Comment by Natim** [comment]
Don't worry about it, thank you for fixing this first one :)

**Comment by anweshknayak** [comment]
Yay thanks @Natim first PR in *notes* merged :tada:

**Comment by Natim** [comment]
Congratulation and thank you for your help :)

**Pull request merged**
