### PR TITLE
Prepare 1.5.0

### PR DESCRIPTION
**Pull request by Natim**
Call for release, all people should update their translation.
Release date after **Tuesday July 25th 12am UTC**

- [ ] Wait for last translation updates and rebase from master before merging.

### CODE REVIEW

**Comment by vladikoff** [comment]
@Natim we need latest changes from master, let's remake this

**Comment by Natim** [comment]
A rebase would be sufficient actually.

**Comment by Natim** [comment]
Done.

**Comment by vladikoff** [comment]
@clouserw this is merging code from master into `production`, is this correct?

**Comment by vladikoff** [comment]
🍰 👍

**Pull request merged**
